lab3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path(
        '',
        views.home,
        name="home"
    ),
    path(
        'send_message',
        views.SendMessageView.as_view(),
        name='send_message'
    ),
    path(
        'signup/',
        views.signup,
        name='signup'
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile (models.Model):
    '''Extension of Django built-in User model'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    messages = models.ManyToManyField('main.Profile', through='Message')

    def __str__(self):
        return self.user.get_username()
    
    def get_absolute_url(self):
        return "/subject/%i/" % self.id


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    '''When user is created, attaches profile to it'''
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()


class Message(models.Model):
    text = models.TextField()
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='senders')
    recipient = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='recipients')

    def __str__(self):
        return self.text
    
    def get_absolute_url(self):
        return "/subject/%i/" % self.id

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Message, Profile

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('__all__')
        exclude = ['sender']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Повідомлення', 'rows': 3}),
            'recipient': forms.Select(
                choices=Profile.objects.all().values_list('id', 'user')
            )
        }


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=30,
        help_text='Required. Enter a valid email address.'
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, TemplateView
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.http import HttpResponseRedirect
from main.models import Message
from main.forms import MessageForm, SignUpForm

class HomeView(TemplateView):
    model = Message
    template_name = 'home.html'



class SendMessageView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        form.instance.sender = self.request.user.profile

        if form.is_valid():
            form.instance.save()
        
        return HttpResponseRedirect(reverse('main:home'))

def home(request):
    form = MessageForm()
    messages = Message.objects.all()
    return render(request, 'home.html', {'form': form, 'messages': messages})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

lab3/templates/base.html
<!doctype html>
{% load static %}

<html lang="en">
    <title>Messenger</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <body style="height: 100vh;"></body>
    <div class="sticky">
        <div class="w3-row w3-bar w3-teal" style="display: block;">
            {% block navbar-items %}
            {% if user.is_authenticated %}
            <a class="w3-button w3-right" href="{% url 'logout' %}?next=/"><b>Вийти</b></a>
            {% else %}
            <a class="w3-button w3-right" href="{% url 'main:signup' %}"><b>Реєстрація</b></a>
            <a class="w3-button w3-right" href="{% url 'login' %}"><b>Вхід</b></a>
            {% endif %}
            {% endblock navbar-items%}
        </div>
    </div>
    
    <div class="w3-row">
        {% block sidebar %}
        {% endblock %}
    
        {% block with-content %}
        {% endblock %}
    </div>
    {% block footer %}
    <br>
    {% endblock %}
    </body>
</html>

lab3/templates/home.html
{% extends "base.html" %}

{% block with-content %}
    <div class="w3-content">
        {% for m in messages %}
        <p class="w3-medium">{{ m.sender }}</p>
        <p class="w3-medium">{{ m.recipient }}</p>
        <p class="w3-medium">{{ m.text }}</p>
        {% endfor %}

        <form action="{% url 'main:send_message' %}" enctype="multiparty/form-data" method="post">
            {% csrf_token %}
            <div>{{ form.as_p }}</div>
            <div><input class="button" type="submit" value="Надіслати"></input></div>
        </form>
    </div>
{% endblock with-content %}

lab3/templates/signup.html
{% extends 'base.html' %}

{% block with-content %}
<div class="w3-content">
    <h1 class="w3-center">Реєстрація</h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            <div>{{ field.label_tag }}</div>
            <div>{{ field }}</div>
            <div>{{ field.errors }}</div>
        </p>
        {% endfor %}
        <button type="submit" class="w3-white w3-border w3-border-black">Зареєструватися</button>
    </form>
</div>
{% endblock %}